### ISSUE TITLE
STO Union location fix

### ISSUE THREAD

**Issue by dlh28** [artsdata-stewards/support-issues#2]
[STO Union](http://kg.artsdata.ca/resource/K14-65) is stated to be located in Wakefield, QC, although they are actually located in Farrellton, QC (a small village near Wakefield). I spoke to STO Union and they preferred to be described as located in La Pêche (the municipality encompassing both Wakefield and Farrellton).

**Comment by saumier** [comment]
@dlh28 I updated the schema:disambiguatingDescription in Artsdata to match Wikidata. This mentions La Pêche.  Incidentally I lived not too far from Wakefield when I was a toddler.
